scriptencoding utf-8
set encoding=utf-8
" keymappings
inoremap jj <esc>
" dracula theme
syntax on
color dracula
" tab = 2 spaces
set tabstop=2 shiftwidth=2 expandtab
set autoindent smartindent
" visible whitespace
set listchars=eol:¬,tab:»·,trail:·,space:·
set list
hi NonText ctermfg=61 ctermbg=NONE cterm=NONE guifg=#6272a4 guibg=NONE gui=NONE
hi SpecialKey ctermfg=61 ctermbg=NONE cterm=NONE guifg=#6272a4 guibg=NONE gui=NONE
" allow backspace
set backspace=indent,eol,start
