DEFAULT_USER="phucanhtran"
ZSH_THEME="dracula"

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH="/Users/phucanhtran/.oh-my-zsh"

plugins=(
  git,
  zsh-autosuggestions
)
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# aliases
# general
alias vz="vim ~/.zshrc"
alias sz="source ~/.zshrc"

# git
alias gac="git add -A && git cz"
alias glo="git log --oneline"
alias gbr="git branch"
alias gch="git checkout"
alias gdiff="git diff"
alias gstat="git status"
alias gpull="git pull"
alias gpup="git push --set-upstream origin"
alias gunstage="git reset"
alias guncommit="git reset HEAD^"
gsquash () {
  git fetch
  git reset $(git merge-base master $1)
}

# parsley
alias parsley="cd ~/parsley"
alias api="cd ~/parsley/api"
alias apis="cd ~/parsley/api && ./do up"
alias apik="cd ~/parsley/api && ./do down"
alias apikk="cd ~/parsley/api && docker-compose down"
alias tks="cd ~/parsley/traefik && make up"
alias my="cd ~/parsley/my-parsley"
alias mys="cd ~/parsley/my-parsley && yarn start"
alias myk="cd ~/parsley/my-parsley && yarn stop"
alias join="cd ~/parsley/join-parsley"
alias joins="cd ~/parsley/join-parsley && npm start"
alias joink="cd ~/parsley/join-parsley && npm stop"
alias on="cd ~/parsley/onboarding"
alias dr="cd ~/parsley/dr-parsley"
alias drs="cd ~/parsley/dr-parsley && npm start"

# js workflow
alias rly="npm run relay"
alias rlyd="cd ~/parsley/relay-devtools && node lib/standalone/launchApp.js"
alias hidegen="printf '{\n\t\"folders\": [\n\t\t{\n\t\t\t\"path\": \"dr-parsley\"\n\t\t}\n\t],\n\t\"settings\": {\"files.exclude\": {\"**/__generated__/\": true}}\n}' > ~/parsley/ph.code-workspace"
alias showgen="printf '{\n\t\"folders\": [\n\t\t{\n\t\t\t\"path\": \"dr-parsley\"\n\t\t}\n\t],\n\t\"settings\": {\"files.exclude\": {\"**/__generated__/\": false}}\n}' > ~/parsley/ph.code-workspace"
alias flo="npm run flow"
alias sto="npm run storybook"
