DEFAULT_USER="phucanhtran"
ZSH_THEME="dracula"

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH="/Users/phucanhtran/.oh-my-zsh"

plugins=(
  git,
  zsh-autosuggestions
)
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# aliases
# general
alias vz="vim ~/.zshrc"
alias sz="source ~/.zshrc"
alias alt="~/magic/alt/mdloader_mac --first --download config.bin --restart"
alias bsf="pbcopy | base64 -D"

# git
alias gaa="git add -A"
alias gac="gaa && npm run commit"
alias gaca="gaa && git commit -n --amend"
alias gam="gaa && git commit -m"
alias gbr="git branch"
alias gbd="git branch -D"
alias gca="git commit -n --amend"
alias gch="git checkout"
alias gchb="git checkout -b"
alias gcherry="git cherry-pick"
alias gchm="git checkout master"
alias gcm="git commit -m"
alias gddev="git push origin --delete develop && gbd develop"
alias gdiff="git diff"
alias glo="git log --oneline"
alias gpdev="gcb develop && gpup develop"
alias gpull="git pull"
alias gpup="git push --set-upstream origin"
alias gstat="git status"
alias gunstage="git reset"
alias guncommit="git reset HEAD^"
gpresquash () {
  git fetch
  git reset $(git merge-base master $1)
}

# python
alias py="python3"
alias pip="pip3"

# parsley
alias parsley="cd ~/parsley"

# parsley apis
alias dapi="cd ~ && ./cloud_sql_proxy -instances=parsley-production-1:us-east1:sage-database=tcp:5432"
alias dapis="cd ~ && ./cloud_sql_proxy -instances=parsley-staging-1:us-east1:sage-database=tcp:5435"
alias dapifwd="kubectl port-forward deployment/data-api-server 8000"

alias nginxs="brew services start nginx"
alias nginxk="brew services stop nginx"

alias papi="cd ~/parsley/sage/product-api"
alias papifwd="nginx && dapifwd"
alias papis="papi && npm start"
alias papist="cp /usr/local/etc/nginx/nginx.conf-staging-papi /usr/local/etc/nginx/nginx.conf && nginxk && nginxs"
alias papilo="cp /usr/local/etc/nginx/nginx.conf-local-papi /usr/local/etc/nginx/nginx.conf && nginxk && nginxs"
alias papigen="papi && npm run gql-gen"
alias papibuild="papi && npm run gcp-build"


# parsley UIs
alias dr="cd ~/parsley/dr-parsley"
alias drs="dr && npm start"
alias drschema="dr && npm run graphql:get-schema"
alias drstartall="brew services start nginx && dr && npm start"

# parsley tools
alias apo="npm run graphql:setup"
alias sto="npm run storybook"
alias testd="npm run test:debug"
alias tests="npm run test --silent"

# personal
alias fruit="cd ~/magic/fruitface && npm run develop"
