
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# aliases
# general
alias vb="vim ~/.bashrc"
alias sb="source ~/.bashrc"

# git
alias gac="git add -A && git cz"
alias glo="git log --oneline"
alias gbr="git branch"
alias gch="git checkout"
alias gdiff="git diff"
alias gstat="git status"
alias gpull="git pull"
alias gpup="git push --set-upstream origin"
g1c () {
  git fetch master
  git reset $(git merge-base master $1)
}

# parsley
alias parsley="cd ~/parsley"
alias api="cd ~/parsley/api"
alias apis="cd ~/parsley/api && ./do up"
alias apik="cd ~/parsley/api && ./do down"
alias tks="cd ~/parsley/traefik && make up"
alias my="cd ~/parsley/my-parsley"
alias mys="cd ~/parsley/my-parsley && yarn start"
alias myk="cd ~/parsley/my-parsley && yarn stop"
alias join="cd ~/parsley/join-parsley"
alias joins="cd ~/parsley/join-parsley && npm start"
alias joink="cd ~/parsley/join-parsley && npm stop"
alias on="cd ~/parsley/onboarding"
